"""
Django settings for isp project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import django_heroku
import dj_database_url

from django.core.management.utils import get_random_secret_key

import cloudinary
import cloudinary.uploader
import cloudinary.api

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_random_secret_key()


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['ispmanager', 'www.ispmanager']

#hsts settings
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_PRELOAD = True
SECURE_HSTS_INCLUDE_SUBDOMAINS = True

#https settings
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",  
    "django.contrib.gis",
    "leaflet",
    "notifications", 
    "crispy_forms",
    "crispy_bootstrap5",
    "chartjs",
    "main"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "isp.urls"



TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "isp.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": "isp",
        "USER": "postgres",
        "PASSWORD": "Tauren",
<<<<<<< HEAD
        "HOST": "localhost",
=======
        "HOST": "127.0.0.1",
>>>>>>> c219da888751f058d059f141933c5fcf2a4a80cd
        "PORT": "5432",
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Nairobi"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
#STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

GDAL_LIBRARY_PATH = os.path.join(BASE_DIR, 'gdal', 'gdal304.dll')

LEAFLET_CONFIG = {
    'DEFAULT_CENTER': (-1.282385, 36.968488),
    'DEFAULT_ZOOM': 14,
    'MAX_ZOOM':23,
    'MIN_ZOOM': 3,
    'CONTROL_DICT': {
        'zoomControl': False,  # Hide the default zoom control
        },
    'SCALE': 'both', 
    'ATTRIBUTION_PREFIX': 'Developed by ConstrumGIS',
    'PLUGINS': {
            'forms': {
                    'js': ['/static/dist/leaflet.ajax.js','/static/plugins/Control.FullScreen.js', '/static/plugins/Leaflet.Coordinates-0.1.5.min.js', '/static/plugins/leaflet.browser.print.js', '/static/plugins/leaflet.zoomhome.min.js','/static/plugins/leaflet-ruler.js', '/static/plugins/Leaflet.LocationShare.js','https://cdn.jsdelivr.net/gh/gokertanrisever/leaflet-ruler@master/src/leaflet-ruler.js','https://unpkg.com/leaflet.pm@latest/dist/leaflet.pm.min.js', '/static/plugins/leaflet-search.js', '/static/plugins/leaflet-measure.js','https://unpkg.com/leaflet-control-geocoder/dist/Control.Geocoder.js'],
                    'css': ['/static/Control.FullScreen.css', '/static/Leaflet.Coordinates-0.1.5.css', '/static/leaflet.zoomhome.css','/static/leaflet-ruler.css','https://unpkg.com/leaflet.pm@latest/dist/leaflet.pm.css','https://cdn.jsdelivr.net/gh/gokertanrisever/leaflet-ruler@master/src/leaflet-ruler.css', '/static/leaflet-search-master/src/leaflet-search.css', '/static/leaflet-measure.css','https://unpkg.com/leaflet-control-geocoder/dist/Control.Geocoder.css'],
            },
        },
}


LOGIN_URL = 'login'
LOGOUT_URL = 'logout'
LOGIN_REDIRECT_URL = 'home' 
LOGOUT_REDIRECT_URL = 'login' 

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

cloudinary.config(
    cloud_name='dgkommeq9',
    api_key='125995954515637',
    api_secret='7UBo6Yy6EWDpklpCL1JiAZLxZXM'
)
<<<<<<< HEAD

django_heroku.settings(locals())
=======
>>>>>>> c219da888751f058d059f141933c5fcf2a4a80cd
