# Generated by Django 4.2.7 on 2023-12-06 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zones",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="zones",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="zones",
            name="photo_name",
        ),
        migrations.RemoveField(
            model_name="zones",
            name="photo_url",
        ),
    ]
