# Generated by Django 4.2.7 on 2023-12-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_zones_latitude_remove_zones_longitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="address",
            field=models.CharField(blank=True, default="", max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="clients",
            name="building_t",
            field=models.CharField(blank=True, default="", max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="clients",
            name="name",
            field=models.CharField(blank=True, default="", max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="clients",
            name="odb_split",
            field=models.CharField(blank=True, default="", max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="clients",
            name="olt",
            field=models.CharField(blank=True, default="", max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="clients",
            name="pon_type",
            field=models.CharField(blank=True, default="", max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="clients",
            name="zone",
            field=models.CharField(blank=True, default="", max_length=254, null=True),
        ),
    ]
