# Generated by Django 4.2.7 on 2023-12-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_zone_delete_zones"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zone",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
