# Generated by Django 4.2.7 on 2023-12-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_notification_is_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="changes",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
